<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            // BBS XR Platinum Silver
            1 => [
                'manufacturer' => 'BBS',
                'model' => 'XR Platinum Silver',
                'code' => 'kgk001',
                'type' => 'Mesh Design, Twin 7 Spoke',
                'color' => 'Silver',
                'size' => '17',
                'price' => 216.60,
                'description' => 'The new BBS “XR” wheel unites opposites. A total of seven clearly shaped Y-spokes pick up on the company‘s classic design language and simultaneously reinterpret it. The striking recess in the centre of the wheel pays homage to former BBS legends. The XR comes in 17" to 20" diameters(depending on the finish) with a variety of PCD patterns, such as 5x120, 5x112 and many more, making it a perfect match for all modern BMW, Audi, and Mercedes-Benz vehicles, along with many Ford cars. Available in gloss black, platinum silver, and satin bronze finish.',
                'picture_name' => 'prod_img_BBS_XR',
                'picture_amount' => 1,
            ],
            2 => [
                'manufacturer' => 'BBS',
                'model' => 'XR Platinum Silver',
                'code' => 'kgk002',
                'type' => 'Mesh Design, Twin 7 Spoke',
                'color' => 'Silver',
                'size' => '18',
                'price' => 245.70,
                'description' => 'The new BBS “XR” wheel unites opposites. A total of seven clearly shaped Y-spokes pick up on the company‘s classic design language and simultaneously reinterpret it. The striking recess in the centre of the wheel pays homage to former BBS legends. The XR comes in 17" to 20" diameters(depending on the finish) with a variety of PCD patterns, such as 5x120, 5x112 and many more, making it a perfect match for all modern BMW, Audi, and Mercedes-Benz vehicles, along with many Ford cars. Available in gloss black, platinum silver, and satin bronze finish.',
                'picture_name' => 'prod_img_BBS_XR',
                'picture_amount' => 1,
            ],
            3 => [
                'manufacturer' => 'BBS',
                'model' => 'XR Platinum Silver',
                'code' => 'kgk003',
                'type' => 'Mesh Design, Twin 7 Spoke',
                'color' => 'Silver',
                'size' => '19',
                'price' => 330.40,
                'description' => 'The new BBS “XR” wheel unites opposites. A total of seven clearly shaped Y-spokes pick up on the company‘s classic design language and simultaneously reinterpret it. The striking recess in the centre of the wheel pays homage to former BBS legends. The XR comes in 17" to 20" diameters(depending on the finish) with a variety of PCD patterns, such as 5x120, 5x112 and many more, making it a perfect match for all modern BMW, Audi, and Mercedes-Benz vehicles, along with many Ford cars. Available in gloss black, platinum silver, and satin bronze finish.',
                'picture_name' => 'prod_img_BBS_XR',
                'picture_amount' => 1,
            ],
            4 => [
                'manufacturer' => 'BBS',
                'model' => 'XR Platinum Silver',
                'code' => 'kgk004',
                'type' => 'Mesh Design, Twin 7 Spoke',
                'color' => 'Silver',
                'size' => '20',
                'price' => 410.23,
                'description' => 'The new BBS “XR” wheel unites opposites. A total of seven clearly shaped Y-spokes pick up on the company‘s classic design language and simultaneously reinterpret it. The striking recess in the centre of the wheel pays homage to former BBS legends. The XR comes in 17" to 20" diameters(depending on the finish) with a variety of PCD patterns, such as 5x120, 5x112 and many more, making it a perfect match for all modern BMW, Audi, and Mercedes-Benz vehicles, along with many Ford cars. Available in gloss black, platinum silver, and satin bronze finish.',
                'picture_name' => 'prod_img_BBS_XR',
                'picture_amount' => 1,
            ],

            //DOTZ Misano
            5 => [
                'manufacturer' => 'Dotz',
                'model' => 'Misano',
                'code' => 'kgk005',
                'type' => 'Concave, Twin 5 Spoke',
                'color' => 'Grey',
                'size' => '17',
                'price' => 206.60,
                'description' => 'The concave construction and the thin spokes pairs resembling delicate tuning forks, make the new Misano unique. VTA approvals for a wide range of car models offer enthusiasts many styling options.',
                'picture_name' => 'prod_img_Dotz_Misano',
                'picture_amount' => 1,
            ],
            6 => [
                'manufacturer' => 'Dotz',
                'model' => 'Misano',
                'code' => 'kgk006',
                'type' => 'Concave, Twin 5 Spoke',
                'color' => 'Grey',
                'size' => '18',
                'price' => 215.70,
                'description' => 'The concave construction and the thin spokes pairs resembling delicate tuning forks, make the new Misano unique. VTA approvals for a wide range of car models offer enthusiasts many styling options.',
                'picture_name' => 'prod_img_Dotz_Misano',
                'picture_amount' => 1,
            ],
            7 => [
                'manufacturer' => 'Dotz',
                'model' => 'Misano',
                'code' => 'kgk007',
                'type' => 'Concave, Twin 5 Spoke',
                'color' => 'Grey',
                'size' => '19',
                'price' => 310.40,
                'description' => 'The concave construction and the thin spokes pairs resembling delicate tuning forks, make the new Misano unique. VTA approvals for a wide range of car models offer enthusiasts many styling options.',
                'picture_name' => 'prod_img_Dotz_Misano',
                'picture_amount' => 1,
            ],
            8 => [
                'manufacturer' => 'Dotz',
                'model' => 'Misano',
                'code' => 'kgk008',
                'type' => 'Concave, Twin 5 Spoke',
                'color' => 'Grey',
                'size' => '20',
                'price' => 339.23,
                'description' => 'The concave construction and the thin spokes pairs resembling delicate tuning forks, make the new Misano unique. VTA approvals for a wide range of car models offer enthusiasts many styling options.',
                'picture_name' => 'prod_img_Dotz_Misano',
                'picture_amount' => 1,
            ],

            // BBS CI-R
            9 => [
                'manufacturer' => 'BBS',
                'model' => 'CI-R',
                'code' => 'kgk009',
                'type' => 'Mesh Design, Twin 7 Spoke',
                'color' => 'Black',
                'size' => '17',
                'price' => 554.60,
                'description' => 'The wheel captivates not only visually with its distinctive, BBS typical Y-spokes, but is also equipped with all kinds of technical finesse. Weight optimization here is a top priority. Thanks to the proven Flow-Forming technology and back-milled spokes, the CI-R is an absolute lightweight construction wheel with a replaceable stainless-steel rim protector.The CI-R comes in 19" and 20" diameters with a variety of PCD patterns, such as 5x120, 5x112 and many more, making it a perfect match for all modern BMW, Audi, and Mercedes-Benz vehicles, along with many Ford cars. Available in satin platinum, satin black and satin titanium finishes.',
                'picture_name' => 'prod_img_BBS_CIR',
                'picture_amount' => 1,
            ],
            10 => [
                'manufacturer' => 'BBS',
                'model' => 'CI-R',
                'code' => 'kgk010',
                'type' => 'Mesh Design, Twin 7 Spoke',
                'color' => 'Black',
                'size' => '18',
                'price' => 612.70,
                'description' => 'The wheel captivates not only visually with its distinctive, BBS typical Y-spokes, but is also equipped with all kinds of technical finesse. Weight optimization here is a top priority. Thanks to the proven Flow-Forming technology and back-milled spokes, the CI-R is an absolute lightweight construction wheel with a replaceable stainless-steel rim protector.The CI-R comes in 19" and 20" diameters with a variety of PCD patterns, such as 5x120, 5x112 and many more, making it a perfect match for all modern BMW, Audi, and Mercedes-Benz vehicles, along with many Ford cars. Available in satin platinum, satin black and satin titanium finishes.',
                'picture_name' => 'prod_img_BBS_CIR',
                'picture_amount' => 1,
            ],
            11 => [
                'manufacturer' => 'BBS',
                'model' => 'CI-R',
                'code' => 'kgk011',
                'type' => 'Mesh Design, Twin 7 Spoke',
                'color' => 'Black',
                'size' => '19',
                'price' => 700.00,
                'description' => 'The wheel captivates not only visually with its distinctive, BBS typical Y-spokes, but is also equipped with all kinds of technical finesse. Weight optimization here is a top priority. Thanks to the proven Flow-Forming technology and back-milled spokes, the CI-R is an absolute lightweight construction wheel with a replaceable stainless-steel rim protector.The CI-R comes in 19" and 20" diameters with a variety of PCD patterns, such as 5x120, 5x112 and many more, making it a perfect match for all modern BMW, Audi, and Mercedes-Benz vehicles, along with many Ford cars. Available in satin platinum, satin black and satin titanium finishes.',
                'picture_name' => 'prod_img_BBS_CIR',
                'picture_amount' => 1,
            ],
            12 => [
                'manufacturer' => 'BBS',
                'model' => 'CI-R',
                'code' => 'kgk012',
                'type' => 'Mesh Design, Twin 7 Spoke',
                'color' => 'Black',
                'size' => '20',
                'price' => 810.00,
                'description' => 'The wheel captivates not only visually with its distinctive, BBS typical Y-spokes, but is also equipped with all kinds of technical finesse. Weight optimization here is a top priority. Thanks to the proven Flow-Forming technology and back-milled spokes, the CI-R is an absolute lightweight construction wheel with a replaceable stainless-steel rim protector.The CI-R comes in 19" and 20" diameters with a variety of PCD patterns, such as 5x120, 5x112 and many more, making it a perfect match for all modern BMW, Audi, and Mercedes-Benz vehicles, along with many Ford cars. Available in satin platinum, satin black and satin titanium finishes.',
                'picture_name' => 'prod_img_BBS_CIR',
                'picture_amount' => 1,
            ],

            // AEZ Steam
            13 => [
                'manufacturer' => 'AEZ',
                'model' => 'Steam',
                'code' => 'kgk013',
                'type' => 'Concave, Multispoke',
                'color' => 'Graphite',
                'size' => '17',
                'price' => 143.60,
                'description' => '„Made in Germany”, multi-spoke rim with a classic design but tuned to modern cars. The diamond-cut face design featuring eleven dimensions offers many application possibilities. From Alfa to Volvo. AEZ is a German wheel company founded in the mid-90s and is well-known for its high-quality wheels. AEZ wheels undergo rigorous testing and are TÜV-certified. They include both classic alloy wheel designs plus wheels created specifically for three premium German car brands: Audi, BMW, and Mercedes.',
                'picture_name' => 'prod_img_AEZ_Steam',
                'picture_amount' => 1,
            ],
            14 => [
                'manufacturer' => 'AEZ',
                'model' => 'Steam',
                'code' => 'kgk014',
                'type' => 'Concave, Multispoke',
                'color' => 'Graphite',
                'size' => '18',
                'price' => 220.70,
                'description' => '„Made in Germany”, multi-spoke rim with a classic design but tuned to modern cars. The diamond-cut face design featuring eleven dimensions offers many application possibilities. From Alfa to Volvo. AEZ is a German wheel company founded in the mid-90s and is well-known for its high-quality wheels. AEZ wheels undergo rigorous testing and are TÜV-certified. They include both classic alloy wheel designs plus wheels created specifically for three premium German car brands: Audi, BMW, and Mercedes.',
                'picture_name' => 'prod_img_AEZ_Steam',
                'picture_amount' => 1,
            ],
            15 => [
                'manufacturer' => 'AEZ',
                'model' => 'Steam',
                'code' => 'kgk015',
                'type' => 'Concave, Multispoke',
                'color' => 'Graphite',
                'size' => '19',
                'price' => 300.00,
                'description' => '„Made in Germany”, multi-spoke rim with a classic design but tuned to modern cars. The diamond-cut face design featuring eleven dimensions offers many application possibilities. From Alfa to Volvo. AEZ is a German wheel company founded in the mid-90s and is well-known for its high-quality wheels. AEZ wheels undergo rigorous testing and are TÜV-certified. They include both classic alloy wheel designs plus wheels created specifically for three premium German car brands: Audi, BMW, and Mercedes.',
                'picture_name' => 'prod_img_AEZ_Steam',
                'picture_amount' => 1,
            ],
            16 => [
                'manufacturer' => 'AEZ',
                'model' => 'Steam',
                'code' => 'kgk016',
                'type' => 'Concave, Multispoke',
                'color' => 'Graphite',
                'size' => '20',
                'price' => 323.23,
                'description' => '„Made in Germany”, multi-spoke rim with a classic design but tuned to modern cars. The diamond-cut face design featuring eleven dimensions offers many application possibilities. From Alfa to Volvo. AEZ is a German wheel company founded in the mid-90s and is well-known for its high-quality wheels. AEZ wheels undergo rigorous testing and are TÜV-certified. They include both classic alloy wheel designs plus wheels created specifically for three premium German car brands: Audi, BMW, and Mercedes.',
                'picture_name' => 'prod_img_AEZ_Steam',
                'picture_amount' => 1,
            ],
            // AEZ Panama
            17 => [
                'manufacturer' => 'AEZ',
                'model' => 'Panama',
                'code' => 'kgk017',
                'type' => 'Concave, Mesh Design',
                'color' => 'Gloss',
                'size' => '17',
                'price' => 292.60,
                'description' => 'AEZ Panama AEZ Panama. A strong partner that will take loads of up to 1,025 kg. The modern, concave cross-spoke rim has been developed especially for premium segment SUVs. VTA and ECE certifications are available for many car models. Panama comes in 19" to 21" wheel diameters with popular PCDs like 5x108, 5x112, 5x120 and more. Available high gloss and gunmetal polished finishes.',
                'picture_name' => 'prod_img_AEZ_Panama',
                'picture_amount' => 1,
            ],
            18 => [
                'manufacturer' => 'AEZ',
                'model' => 'Panama',
                'code' => 'kgk018',
                'type' => 'Concave, Mesh Design',
                'color' => 'Gloss',
                'size' => '18',
                'price' => 345.70,
                'description' => 'AEZ Panama AEZ Panama. A strong partner that will take loads of up to 1,025 kg. The modern, concave cross-spoke rim has been developed especially for premium segment SUVs. VTA and ECE certifications are available for many car models. Panama comes in 19" to 21" wheel diameters with popular PCDs like 5x108, 5x112, 5x120 and more. Available high gloss and gunmetal polished finishes.',
                'picture_name' => 'prod_img_AEZ_Panama',
                'picture_amount' => 1,
            ],
            19 => [
                'manufacturer' => 'AEZ',
                'model' => 'Panama',
                'code' => 'kgk019',
                'type' => 'Concave, Mesh Design',
                'color' => 'Gloss',
                'size' => '19',
                'price' => 414.00,
                'description' => 'AEZ Panama AEZ Panama. A strong partner that will take loads of up to 1,025 kg. The modern, concave cross-spoke rim has been developed especially for premium segment SUVs. VTA and ECE certifications are available for many car models. Panama comes in 19" to 21" wheel diameters with popular PCDs like 5x108, 5x112, 5x120 and more. Available high gloss and gunmetal polished finishes.',
                'picture_name' => 'prod_img_AEZ_Panama',
                'picture_amount' => 1,
            ],
            20 => [
                'manufacturer' => 'AEZ',
                'model' => 'Panama',
                'code' => 'kgk020',
                'type' => 'Concave, Mesh Design',
                'color' => 'Gloss',
                'size' => '20',
                'price' => 493.00,
                'description' => 'AEZ Panama AEZ Panama. A strong partner that will take loads of up to 1,025 kg. The modern, concave cross-spoke rim has been developed especially for premium segment SUVs. VTA and ECE certifications are available for many car models. Panama comes in 19" to 21" wheel diameters with popular PCDs like 5x108, 5x112, 5x120 and more. Available high gloss and gunmetal polished finishes.',
                'picture_name' => 'prod_img_AEZ_Panama',
                'picture_amount' => 1,
            ],
            // Dotz Suzuka
            21 => [
                'manufacturer' => 'Dotz',
                'model' => 'Suzuka',
                'code' => 'kgk021',
                'type' => 'Concave, Mesh Design',
                'color' => 'Black',
                'size' => '17',
                'price' => 242.60,
                'description' => 'When DOTZ was integrated into the ALCAR Group as an existing brand in 1999, it was just a name. Now, 20 years later, it has become a passion, characterised by commitment, professionalism and above all, excitement. DOTZ buyers appreciate not only the style but, more importantly, its safe products that have been put to the acid test, have certified roadworthiness, and are TPMS ready.',
                'picture_name' => 'prod_img_Dotz_Suzuka',
                'picture_amount' => 1,
            ],
            22 => [
                'manufacturer' => 'Dotz',
                'model' => 'Suzuka',
                'code' => 'kgk022',
                'type' => 'Concave, Mesh Design',
                'color' => 'Black',
                'size' => '18',
                'price' => 265.00,
                'description' => 'When DOTZ was integrated into the ALCAR Group as an existing brand in 1999, it was just a name. Now, 20 years later, it has become a passion, characterised by commitment, professionalism and above all, excitement. DOTZ buyers appreciate not only the style but, more importantly, its safe products that have been put to the acid test, have certified roadworthiness, and are TPMS ready.',
                'picture_name' => 'prod_img_Dotz_Suzuka',
                'picture_amount' => 1,
            ],
            23 => [
                'manufacturer' => 'Dotz',
                'model' => 'Suzuka',
                'code' => 'kgk023',
                'type' => 'Concave, Mesh Design',
                'color' => 'Black',
                'size' => '19',
                'price' => 330.40,
                'description' => 'When DOTZ was integrated into the ALCAR Group as an existing brand in 1999, it was just a name. Now, 20 years later, it has become a passion, characterised by commitment, professionalism and above all, excitement. DOTZ buyers appreciate not only the style but, more importantly, its safe products that have been put to the acid test, have certified roadworthiness, and are TPMS ready.',
                'picture_name' => 'prod_img_Dotz_Suzuka',
                'picture_amount' => 1,
            ],
            24 => [
                'manufacturer' => 'Dotz',
                'model' => 'Suzuka',
                'code' => 'kgk024',
                'type' => 'Concave, Mesh Design',
                'color' => 'Black',
                'size' => '20',
                'price' => 387.00,
                'description' => 'When DOTZ was integrated into the ALCAR Group as an existing brand in 1999, it was just a name. Now, 20 years later, it has become a passion, characterised by commitment, professionalism and above all, excitement. DOTZ buyers appreciate not only the style but, more importantly, its safe products that have been put to the acid test, have certified roadworthiness, and are TPMS ready.',
                'picture_name' => 'prod_img_Dotz_Suzuka',
                'picture_amount' => 1,
            ],
        ];

        foreach ($data as $product) {
            \App\Models\Product::create([
                'manufacturer' => $product['manufacturer'],
                'model' => $product['model'],
                'code' => $product['code'],
                'type' => $product['type'],
                'color' => $product['color'],
                'size' => $product['size'],
                'price' => $product['price'],
                'description' => $product['description'],
                'picture_name' => $product['picture_name'],
                'picture_amount' => $product['picture_amount'],
            ]);

        }

    }
}